//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSEMBLY_AS083_007
    {
        public string ASSEMBLY_CODE { get; set; }
        public System.DateTime RECORED_TIME { get; set; }
        public string PCI_CODE { get; set; }
        public string CAR_TYPE { get; set; }
        public string RUN_STATUS { get; set; }
        public string OPERATOR_ID { get; set; }
        public string ANGLE_UCL { get; set; }
        public string ANGLE_LSL { get; set; }
        public string TORGUE_UCL { get; set; }
        public string TORGUE_LSL { get; set; }
        public string TOTAL { get; set; }
        public string RESULT { get; set; }
        public string ERROR_CODE { get; set; }
        public string CYCLE_TIME { get; set; }
        public string GLASSLABEL { get; set; }
        public string TORGUE_1_ { get; set; }
        public string TORGUE_2_ { get; set; }
        public string TORGUE_3_ { get; set; }
        public string TORGUE_4_ { get; set; }
        public string TORGUE_5_ { get; set; }
        public string TORGUE_6_ { get; set; }
        public string ANGLE_1_ { get; set; }
        public string ANGLE_2_ { get; set; }
        public string ANGLE_3_ { get; set; }
        public string ANGLE_4_ { get; set; }
        public string ANGLE_5_ { get; set; }
        public string ANGLE_6_ { get; set; }
        public string RepairStatus { get; set; }
    }
}
