//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSEMBLY_AS083_011
    {
        public string ASSEMBLY_CODE { get; set; }
        public System.DateTime RECORED_TIME { get; set; }
        public string PCI_CODE { get; set; }
        public string CAR_TYPE { get; set; }
        public string RUN_STATUS { get; set; }
        public string OPERATOR_ID { get; set; }
        public string ROLL_SAP { get; set; }
        public string GALSS_CLOSE_FORCE { get; set; }
        public string GALSS_TOILT_FORCE { get; set; }
        public string ROLL_CLOSE_FORCE { get; set; }
        public string GLASS_MOTOR_CURRENT { get; set; }
        public string ROLL_MOTOR_CURRENT { get; set; }
        public string ROLL_SAG_UCL { get; set; }
        public string ROLL_SAG_LSL { get; set; }
        public string GALSS_CLOSE_FORCE_UCL { get; set; }
        public string GALSS_CLOSE_FORCE_LSL { get; set; }
        public string GALSS_TOILT_FORCE_UCL { get; set; }
        public string GALSS_TOILT_FORCE_LSL { get; set; }
        public string ROLL_CLOSE_FORCE_UCL { get; set; }
        public string ROLL_CLOSE_FORCE_LSL { get; set; }
        public string GLASS_MOTOR_CURRENT_UCL { get; set; }
        public string GLASS_MOTOR_CURRENT_LSL { get; set; }
        public string ROLL_MOTOR_CURRENT_UCL { get; set; }
        public string ROLL_MOTOR_CURRENT_LSL { get; set; }
        public string TOTAL { get; set; }
        public string RESULT { get; set; }
        public string ERROR_CODE { get; set; }
        public string CYCLE_TIME { get; set; }
        public string RepairStatus { get; set; }
    }
}
