//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSEMBLY_AS083_005
    {
        public string ASSEMBLY_CODE { get; set; }
        public System.DateTime RECORED_TIME { get; set; }
        public string PCI_CODE { get; set; }
        public string CAR_TYPE { get; set; }
        public string RUN_STATUS { get; set; }
        public string OPERATOR_ID { get; set; }
        public string GALSS_PHASE_L { get; set; }
        public string GALSS_PHASE_R { get; set; }
        public string GALSS_PHASE_D_VALUE { get; set; }
        public string ROLL_PHASE_R { get; set; }
        public string ROLL_PHASE_L { get; set; }
        public string ROLL_PHASE_D_VALUE { get; set; }
        public string GLASS_MOTOR_CURRENT { get; set; }
        public string ROLL_MOTOR_CURRENT { get; set; }
        public string GALSS_PHASE_L_UCL { get; set; }
        public string GALSS_PHASE_L_LSL { get; set; }
        public string GALSS_PHASE_R_UCL { get; set; }
        public string GALSS_PHASE_R_LSL { get; set; }
        public string ROLL_PHASE_L_UCL { get; set; }
        public string ROLL_PHASE_L_LSL { get; set; }
        public string ROLL_PHASE_R_UCL { get; set; }
        public string ROLL_PHASE_R_LSL { get; set; }
        public string GLASS_MOTOR_CURRENT_UCL { get; set; }
        public string GLASS_MOTOR_CURRENT_LSL { get; set; }
        public string ROLL_MOTOR_CURRENT_UCL { get; set; }
        public string ROLL_MOTOR_CURRENT_LSL { get; set; }
        public string ECU_CODE_1_ { get; set; }
        public string ECU_CODE_2_ { get; set; }
        public string TOTAL { get; set; }
        public string RESULT { get; set; }
        public string ERROR_CODE { get; set; }
        public string CYCLE_TIME { get; set; }
        public string GALSS_PHASE_D_VALUE_LSL { get; set; }
        public string GALSS_PHASE_D_VALUE_UCL { get; set; }
        public string ROLL_PHASE_D_VALUE_LSL { get; set; }
        public string ROLL_PHASE_D_VALUE_UCL { get; set; }
        public string RepairStatus { get; set; }
        public string ROLL_CODE { get; set; }
    }
}
