//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSEMBLY_AS083_018
    {
        public string ASSEMBLY_CODE { get; set; }
        public System.DateTime RECORED_TIME { get; set; }
        public string PCI_CODE { get; set; }
        public string CAR_TYPE { get; set; }
        public string RUN_STATUS { get; set; }
        public string OPERATOR_ID { get; set; }
        public string NOISE_L_OPEN { get; set; }
        public string NOISE_L_CLOSE { get; set; }
        public string NOISE_R_OPEN { get; set; }
        public string NOISE_R_CLOSE { get; set; }
        public string NOISE_MOTOR { get; set; }
        public string NOISE_MOTOR_UCL { get; set; }
        public string NOISE_MOTOR_LSL { get; set; }
        public string GLASS_MOTOR_SF_V { get; set; }
        public string GLASS_MOTOR_STATUS { get; set; }
        public string ROLL_MOTOR_SF_V { get; set; }
        public string ROLL_MOTOR_STATUS { get; set; }
        public string ABMORMAL_NOISE_STATUS { get; set; }
        public string TOTAL { get; set; }
        public string RESULT { get; set; }
        public string ERROR_CODE { get; set; }
        public string CYCLE_TIME { get; set; }
        public string ROUND_COUNT { get; set; }
        public string ROUND_FLAG { get; set; }
        public string ROUND_MAX { get; set; }
        public string ROUND_MIN { get; set; }
        public string NOISE_L_LSL { get; set; }
        public string NOISE_L_UCL { get; set; }
        public string NOISE_R_LSL { get; set; }
        public string NOISE_R_UCL { get; set; }
        public string ROUNDD_AVG { get; set; }
        public string ROUND_CHANGE { get; set; }
        public string ROUND_CHANGE_MAX { get; set; }
        public string ROUND_CHANGE_MIN { get; set; }
        public string ROUND_TYPE { get; set; }
        public string ROUND_ZERO { get; set; }
        public string RepairStatus { get; set; }
    }
}
