//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ATRS_QUALEntities : DbContext
    {
        public ATRS_QUALEntities()
            : base("name=ATRS_QUALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACDBONDING_AS082_027> ACDBONDING_AS082_027 { get; set; }
        public virtual DbSet<ACDBONDING_AS082_028> ACDBONDING_AS082_028 { get; set; }
        public virtual DbSet<ACDBONDING_AS082_029> ACDBONDING_AS082_029 { get; set; }
        public virtual DbSet<ACDBONDING_AS082_030> ACDBONDING_AS082_030 { get; set; }
        public virtual DbSet<ACDBONDING_AS082_031> ACDBONDING_AS082_031 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_001> ASSEMBLY_AS083_001 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_003_L> ASSEMBLY_AS083_003_L { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_003_R> ASSEMBLY_AS083_003_R { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_005> ASSEMBLY_AS083_005 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_006> ASSEMBLY_AS083_006 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_007> ASSEMBLY_AS083_007 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_008> ASSEMBLY_AS083_008 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_011> ASSEMBLY_AS083_011 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_012> ASSEMBLY_AS083_012 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_013> ASSEMBLY_AS083_013 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_014> ASSEMBLY_AS083_014 { get; set; }
        public virtual DbSet<ASSEMBLY_AS083_018> ASSEMBLY_AS083_018 { get; set; }
        public virtual DbSet<PRODUCT_ACD_INFO> PRODUCT_ACD_INFO { get; set; }
        public virtual DbSet<PRODUCT_ASSEMBLY_INFO> PRODUCT_ASSEMBLY_INFO { get; set; }
    
        public virtual int sp_Product_AS082_027(string strCode, string strCarType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS082_027", strCodeParameter, strCarTypeParameter);
        }
    
        public virtual int sp_Product_AS082_028(string strCode, string strCarType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS082_028", strCodeParameter, strCarTypeParameter);
        }
    
        public virtual int sp_Product_AS082_029(string strCode, string strCarType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS082_029", strCodeParameter, strCarTypeParameter);
        }
    
        public virtual int sp_Product_AS082_030(string strCode, string strCarType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS082_030", strCodeParameter, strCarTypeParameter);
        }
    
        public virtual int sp_Product_AS082_031(string strCode, string strCarType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS082_031", strCodeParameter, strCarTypeParameter);
        }
    
        public virtual int sp_Product_AS083_001(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_001", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_003_L(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_003_L", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_003_R(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_003_R", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_005(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_005", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_006(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_006", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_007(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_007", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_008(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_008", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_011(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_011", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_012(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_012", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_013(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_013", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_014(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_014", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    
        public virtual int sp_Product_AS083_018(string strCode, string strCarType, string strType)
        {
            var strCodeParameter = strCode != null ?
                new ObjectParameter("strCode", strCode) :
                new ObjectParameter("strCode", typeof(string));
    
            var strCarTypeParameter = strCarType != null ?
                new ObjectParameter("strCarType", strCarType) :
                new ObjectParameter("strCarType", typeof(string));
    
            var strTypeParameter = strType != null ?
                new ObjectParameter("strType", strType) :
                new ObjectParameter("strType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Product_AS083_018", strCodeParameter, strCarTypeParameter, strTypeParameter);
        }
    }
}
